/**
 * Type for unique identifiers generated by nanoid
 * Represents the specific format of IDs used throughout the system
 */
export type EntityId = string & { readonly _entityId: unique symbol };

/**
 * Creates a strongly-typed ID from a string
 * @param id - Raw string ID
 * @returns Typed EntityId
 */
export function createEntityId(id: string): EntityId {
    return id as EntityId;
}