name: Deploy App and Storybook

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

              # Extract repo name for path configuration
            - name: Extract repo name
              run: echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV

            # Build the main app
            - name: Build app
              run: npm run build

            # Build Storybook
            - name: Build Storybook
              run: npm run build-storybook

            # Deploy both to GitHub Pages with proper structure
            - name: Prepare combined deployment
              run: |
                  # Create a combined directory
                  mkdir -p ./combined-deploy

                  # Copy main app to root
                  cp -r dist/* ./combined-deploy/ || echo "Main app build directory not found or empty"

                  # Copy Storybook to /storybook subdirectory
                  mkdir -p ./combined-deploy/storybook
                  cp -r storybook-static/* ./combined-deploy/storybook/ || echo "Storybook build directory not found or empty"

                  # Verify the structure
                  echo "Main app files:"
                  ls -la ./combined-deploy || echo "No main app files"
                  echo "Storybook files:"
                  ls -la ./combined-deploy/storybook || echo "No Storybook files"

            # Deploy to GitHub Pages
            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: combined-deploy
                  branch: gh-pages
                  clean: true

            # Display deployment information
            - name: Display deployment info
              run: |
                  echo "Deployment completed."
                  echo "Your app should be available at: https://${{ github.repository_owner }}.github.io/${{ env.REPO_NAME }}/"
                  echo "Your Storybook should be available at: https://${{ github.repository_owner }}.github.io/${{ env.REPO_NAME }}/storybook/"
